substitutions:
  name: esp32-s3-box-3-640554
  friendly_name: Jarvis
micro_wake_word:
  vad:
    model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/main/models/v2/vad.json
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret jarviskey
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret otapassword

esp32:
  framework:
    sdkconfig_options:
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

logger: 
  level: VERBOSE

external_components:
  - source: 
      type: local
      path: /config
    components: [ openai_assistant ]

packages:
  #- !include esp32-s3-box-3.yaml
  - !include esp32-openai.yaml
  #- !include sen66.yaml
  #- !include debug.yaml
  #- !include media_buttons.yaml 
  #- !include alarm.yaml
  #- !include clock.yaml
